### ISSUE TITLE
Headers for test files not updated

### ISSUE THREAD

**Issue by davidmweber** [sbt/sbt-header#146]
Using the most basic setup, `sbt headerCreate` only updates the files in `Compile` (src/main), not `Test` (src/test) . If you use `enablePlugins(AutomateHeaderPlugin)` then the test files are updated as expected. The project located at  https://github.com/8eo/boris/blob/header-update/build.sbt exhibits this behaviour. Steps to replicate:

- Clone the repository at `git@github.com:8eo/boris.git` and checkout the header-update branch.
- Note all files in src/main have the correct Apache headers while the src/test files have short proprietary headers
- Run `sbt headerCreate`. Note the test files do not get updated to Apache-2.0 licenses
- For extra credit, add `enablePlugins(AutomateHeaderPlugin)` and run `sbt test`. Test files now get updated.

**Comment by hseeberger** [comment]
Thanks for the thorough description. Yet this is expected behavior.

Not sure how familiar you are with sbt, but most tasks (like headerCreate) can be scoped, e.g. to a configuration like `compile` or `test`. And, if you omit the configuration, `compile` will be used as a default.

So essentially what you are doing is: `sbt compile:headerCreate`.

And I bet, that if you run `sbt test:headerCreate`, your test sources will get some header love, too.

**Comment by davidmweber** [comment]
Ah!! Missed that subtlety! Much appreciated.
