### ISSUE TITLE
Write LICENSE file to src/main/resources

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt-header#42]
It would be nice if sbt-header would (maybe optionally) be able to write the LICENSE file to `src/main/resources`.

**Comment by britter** [comment]
It is pretty uncommon to have the LICENSE file under `src/main/resources`. The `src/main/resources` directory is for application resources (which the LICENSE file is not). Usually you put it in the top level directory so that anybody who need to know the license can see it.

Apache License even mandates to put the [LICENSE file in the top level directory](http://www.apache.org/dev/apply-license.html):

> To apply the ALv2 to a new software distribution, include one copy of the license text by copying the file:
>
> http://www.apache.org/licenses/LICENSE-2.0.txt
>
> into a file called LICENSE in the top directory of your distribution.

Well, okay you could argue that source repository is not identical to your distribution. But then you would have to configure your build to move the file to the top level directory during your release build.

**Comment by hseeberger** [comment]
I agree that it's uncommon, but you already explained the reason: it must be distributed.

Would be good to take a look at other sbt based projects (e.g. Akka) to understand how they deal with it.

**Comment by hseeberger** [comment]
All right, sbt-fresh 1.4.1 now (a) allows to specify a license and (b) writes the LICENSE file to the binary package (JAR).
