### ISSUE TITLE
Derive configuration from project meta data

### ISSUE THREAD

**Issue by britter** [sbt/sbt-header#44]
At the moment, for using sbt-header I always have to add something like:

```scala
headers := Map(
  "scala" -> Apache2_0("2016", "Benedikt Ritter"),
  "conf" -> Apache2_0("2016", "Benedikt Ritter", "#")
)
```

This feels redundant, since I've to copy the some block for all projects. So it would be nice if the plugin could derive it's configuration from the [project meta data](http://www.scala-sbt.org/0.13/docs/Howto-Project-Metadata.html):

- use `startYear` for the `yyyy` parameter
- use `organizationName` for the `copyrightOwner` parameter
- use the value of `licenses` if there is only one entry to chose the appropriate `License` implementation
- add a file to header style mapping, so that the C block comment style is applied to Scala, Groovy, and Java file, for example

I'm happy to contribute a PR, but I'd like to discuss how to implement this change first.

**Comment by fommil** [comment]
![is it worth the time?](https://imgs.xkcd.com/comics/is_it_worth_the_time.png)

**Comment by britter** [comment]
@fommil so is this a "no"? :smile:

**Comment by fommil** [comment]
I think it might be useful but the amount of time it'll save is not going to be particularly high. You'll need to provide all kinds of overrides so this will potentially end up complicating matters.

Be aware that the organisation suggestion is legally incorrect. Copyright is owned by whoever created the files, and in some countries cannot be transferred. Most github organisations are not legal entities.

Maybe it'd be just as useful to come up with a way of integrating some of the repeated data into the constructors? i.e. a convenient constructor for `headers` so that it is a one liner.

**Comment by britter** [comment]
@fommil I'm getting your point.

I think the comment style auto detection would be useful. Maybe we should just implement that. So implementing your proposal could look something like this:

```scala
headers := createWith(license = Apache2_0, year = "2016", copyrightOwner = "John Doe")
```

with:

```scala
def createWith(license: License, year: String, copyrightOwner: String) = {
  Map(
    "scala" -> license(year, copyrightOwner, "*")
    "java" -> license(year, copyrightOwner, "*"),
    "groovy" -> license(year, copyrightOwner, "*"),
    "conf" -> license(year, copyrightOwner, "#"),
    "properties" -> license(year, copyrightOwner, "#"),
    "yml" -> license(year, copyrightOwner, "#")
    // more default mappings
  )
}
```

WDYT?

**Comment by fommil** [comment]
Yeah, that's very useful! And people can pass in the `year` from the metadata if they have it, and you could potentially also provide a `URL => License` table lookup so that people can reuse their URLs.

**Comment by britter** [comment]
Okay, I'll prepare a PR for the default comment style to file type mapping. :+1:
