### ISSUE TITLE
Add headers to managed sources

### ISSUE THREAD

**Issue by nrinaudo** [sbt/sbt-header#69]
The current plugin "only" adds / updates headers on unmanaged sources.

It would be nice if it dealt with managed sources as well, at least optionally - I'm using sbt-boilerplate to generate some boilerplate code, and would love for the generated code to have proper headers. I can probably already get something working, by playing with `unmanagedSources in createHeaders` and updating the supported extensions, but it would be cleaner to have a setting like `supportManagedSources`.

If this is seen as interesting, I'd be happy to have a go at a PR.

**Comment by britter** [comment]
@nrinaudo I'm currently working on #64 where I also need to have additional files processed (in my case Twirl templates). Currently I'm planning to add some documentation on how to add those files in the user build:

```scala
unmanagedSources.in(Compile, createHeaders) ++= sources.in(Compile, TwirlKeys.compileTemplates)
```

In the twirl case there is no other way to support this, because we would have to define a dependency to Twirl in order to use `TwirlKeys` from inside sbt-header. I think it's better to let users define what sbt-header pick up. In your case it is okay to add all managedSources to the files, sbt-header picks up. But there may be other users where this will mess up their build. Would it work for you to define something like:

```scala
unmanagedSources.in(Compile, createHeaders) ++= managedSources.in(Compile)
```

It would even better to also only add those managedSources which are created by sbt-boilerplate. This way you have fine grained control over what is been created.

**Comment by nrinaudo** [comment]
@britter This makes sense. In my specific use case, I'm probably going to run sbt-header on the boilerplate templates rather than on the output Scala files, but yes, it's probably better not to force sbt-header on managed sources.

As far as I'm concerned, this issue can be closed - I have a solution for my use case, and understand how my proposed solution might be more damaging than helpful, at least in some cases, and does not address the problem in its entirety anyway.

**Comment by britter** [comment]
@nrinaudo maybe we can add your solution for sbt-boilerplate templates to README.md?

**Comment by nrinaudo** [comment]
Sure, as soon as I've put something together, I'll show you and, if you like it, I'll make a PR on the README.

**Comment by britter** [comment]
Yes, that would be awesome!

**Comment by nrinaudo** [comment]
It's not the most complicated (not the most beautiful) thing in the world:

```scala
def addBoilerplate(confs: Configuration*) = confs.foldLeft(List.empty[Setting[_]]) { (acc, conf) =>
  acc ++ (unmanagedSources in (conf, createHeaders) := (((sourceDirectory in conf).value / "boilerplate") ** "*.template").get)
}

addBoilerplate(Compile, Test)
```

This adds `src/{conf}/boilerplate/**.scala` in the list of files handled by sbt-headers for `conf`, where `conf` is either `Compile` or `Test`.
